FROM eclipse-temurin:8-jre-alpine
MAINTAINER "sine.wang" <sinecelia.wang@gmail.com>

ARG VERSION=0.4.7.9
ENV COS_VERSION=${VERSION}
ENV COS_PREFIX="cosbench-"
ENV COS_SUFFIX="-sineio"
ENV COS_FILENAMEEXT=".tar.gz"

WORKDIR /

ADD ${COS_PREFIX}${COS_VERSION}${COS_SUFFIX}${COS_FILENAMEEXT} .

RUN echo 'Asia/Shanghai' > /etc/timezone \ 
    && mv /${COS_PREFIX}${COS_VERSION}${COS_SUFFIX} /cosbench \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update \
    && apk add --no-cache bash curl nmap-ncat busybox-extras \
    && rm -f /bin/sh && ln -s /bin/bash /bin/sh


WORKDIR /cosbench

COPY start-cosbench.sh .

CMD ["sh", "/cosbench/start-cosbench.sh"]

